### ISSUE TITLE
Add logError

### ISSUE THREAD

**Issue by DanoneGrosso-dev** [hSel3triK/discord.js-handler#5]
Olá, vim dar minha sugestão p/ a LIB. 
minha sugestão é:  Add o LogError

P/q serve o LogError??
R: LogError, serve p/ indentificar o erro e mandar por terminal.
ex: 
```js
// dentro da client
const handler = new Handler({
    client: new Client(),
    token: process.env.token,
    eventsFolder: './events',
    commandsFolder: './commands',

// LogError: Indentifica algum erro, e manda p/ o terminal do bot.
LogError: true
});
```

~~ n expliquei mt bem... mas ok, essa era minha sugestão ~~

**Comment by hSel3triK** [comment]
Boa noite. Poderias, por favor, dar mais detalhe? Não consegui perceber exatamente a sugestão, foi um pouco vaga. O handler já tem a opção verbose, que manda para a consola os eventos e comandos que foram carregados, e, caso seja um erro por parte do utilizador, o console deverá mandar o erro na consola direito. Não percebi se envolve algo relacionado a isto.
